.pragma library

var COL_COUNT = 6;
var ROW_COUNT = 8;
var VELOCITY = 400
var NULL = -30
var UP_COUNT = 5
var START_COUNT_SPARKS = 10

var CELL_SPACING = 3;
var FONT_SIZE = 40
var INPUT_SIZE = 100
var SCORES_LIST_ITEM_HEIGHT = 45
var MAX_LENGHT = 7
