.pragma library

var COL_COUNT = 6;
var ROW_COUNT = 8;
var VELOCITY = 380
var NULL = -30
var UP_COUNT = 6
var START_COUNT_SPARKS = 10

var CELL_SPACING = 3;
var FONT_SIZE = 30
var HELP_FONT_SIZE = 23;
var INPUT_SIZE = 130
var SCORES_LIST_ITEM_HEIGHT = 35
var MAX_LENGHT = 7
